# Generated by Django 3.0.7 on 2020-09-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('people', models.PositiveIntegerField()),
                ('need_gloves', models.BooleanField(default=False)),
                ('need_faceshields', models.BooleanField(default=False)),
                ('need_facemasks', models.BooleanField(default=False)),
                ('notes', models.TextField(default='Default desc.', max_length=5000)),
                ('long', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
            ],
        ),
    ]
