# Generated by Django 3.0.7 on 2020-09-06 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200905_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
