# Generated by Django 3.0.7 on 2020-09-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200906_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
