# Generated by Django 3.0.7 on 2020-09-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200906_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('desc', models.TextField(default='Default desc.', max_length=5000)),
                ('amount_gloves', models.PositiveIntegerField()),
                ('amount_faceshields', models.PositiveIntegerField()),
                ('amount_facemasks', models.PositiveIntegerField()),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
            ],
        ),
        migrations.AlterField(
            model_name='individual',
            name='notes',
            field=models.TextField(default='Default notes.', max_length=5000),
        ),
    ]
