# Generated by Django 3.0.7 on 2020-09-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200906_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributor',
            old_name='email',
            new_name='address',
        ),
        migrations.AddField(
            model_name='distributor',
            name='website',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
