# Generated by Django 3.0.7 on 2020-09-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200906_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributor',
            old_name='amount_facemasks',
            new_name='nofacemasks',
        ),
        migrations.RenameField(
            model_name='distributor',
            old_name='amount_faceshields',
            new_name='nofaceshields',
        ),
        migrations.RenameField(
            model_name='distributor',
            old_name='amount_gloves',
            new_name='nogloves',
        ),
        migrations.AlterField(
            model_name='individual',
            name='notes',
            field=models.TextField(default='Default desc.', max_length=5000),
        ),
    ]
