# Generated by Django 3.0.7 on 2020-09-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200906_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='long',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='long',
        ),
        migrations.AddField(
            model_name='individual',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
