# Generated by Django 3.0.7 on 2020-09-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200906_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributor',
            old_name='nofacemasks',
            new_name='nomasks',
        ),
        migrations.RenameField(
            model_name='distributor',
            old_name='nofaceshields',
            new_name='noshields',
        ),
    ]
